baseURL: http://example.org/
languageCode: en-us
title: My New Hugo Site

module:
  imports:
    - path: github.com/imfing/hextra

markup:
  # allow raw html
  goldmark:
    renderer:
      # TODO: check if it works fine also with unsafe renderer turned off
      unsafe: true

  # enable hextra syntax highlight
  highlight:
    noClasses: false

menu:
  main:
    - name: Docs
      pageRef: /docs
      weight: 1
    - name: About
      pageRef: /about
      weight: 2
    - name: Search
      weight: 4
      params:
        type: search

params:
  navbar:
    displayTitle: true
    displayLogo: false

  footer:
    displayCopyright: false
    displayPoweredBy: true
